name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile GCC
        run: gcc main.c -o cncursesfirstprogram -lncurses

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: c-ncurses-first-program-linux
          path: cncursesfirstprogram
